# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['../Ogresync.py'],
    pathex=['/home/gloup/Personal/Development/Ogresync'],
    binaries=[],
    datas=[('../assets', 'assets')],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'tkinter.scrolledtext',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'tkinter.simpledialog',
        'subprocess',
        'threading',
        'psutil',
        'pyperclip',
        'requests',
        'shlex',
        'platform',
        'webbrowser',
        'packaging_utils',
        'ui_elements',
        'wizard_steps',
        'github_setup',
        'setup_wizard',
        'Stage1_conflict_resolution',
        'stage2_conflict_resolution',
        'backup_manager',
        'conflict_resolution_integration',
        'offline_sync_manager',
        'enhanced_auto_sync',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'PIL',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'wx',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Ogresync',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
